### ISSUE TITLE
decoratorsBeforeExport error when parsing JS files

### ISSUE THREAD

**Issue by IgnaceMaes** [ijlee2/codemod-utils#68]
I've been going through the tutorial, amazing job!

When creating an AST traversal matching on `visitClassDeclaration` in a JavaScript file, I'm seeing the following error when a class has a decorator:

```
<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:63
}, descriptor)), Object.assign(new constructor(), properties));
                               ^

SyntaxError: Decorators must be placed *after* the 'export' keyword. Remove the 'decoratorsBeforeExport: false' option to use the '@decorator export class {}' syntax. (8:0)
    at instantiate (<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:63:32)
    at constructor (<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:358:12)
    at JSXParserMixin.raise (<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:3207:19)
    at JSXParserMixin.parseDecorators (<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:12735:14)
    at JSXParserMixin.parseStatementLike (<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:12536:25)
    at JSXParserMixin.parseModuleItem (<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:12515:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:13139:36)
    at JSXParserMixin.parseBlockBody (<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:13132:10)
    at JSXParserMixin.parseBlockBody (<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:520:11)
    at JSXParserMixin.parseProgram (<redacted-project-root>/node_modules/.pnpm/@babel+parser@7.22.10/node_modules/@babel/parser/lib/index.js:12414:10) {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'DecoratorExportClass',
  loc: Position { line: 8, column: 0, index: 212 },
  pos: [Getter/Setter]
}

Node.js v18.16.0
```

on e.g. the following component:

```
// imports ...

@tagName('')
export default class FooBarComponent extends Component {
  foo = 9000;
}
```

When changing the `decoratorsBeforeExport` option to true in the [javascript config](https://github.com/ijlee2/codemod-utils/blob/main/packages/ast/javascript/src/ast/javascript.ts#L39) for babel it _does_ work. Is this disabled on purpose? As putting the decorator in front of the export keyword is a common Ember pattern. In a TypeScript file this works as expected.

**Comment by ijlee2** [comment]
`@codemod-utils/ast-javascript@1.1.0` will fix this issue. (Sorry for the late response. Completely forgot about it.)
